dupe-amount: 5

blacklisted-items:
  - BEDROCK
  - COMMAND_BLOCK
  - BARRIER
  - STRUCTURE_BLOCK
  - END_PORTAL_FRAME
  - BAMBOO
  - SEA_PICKLE
  - DRAGON_EGG
  - ENCHANTED_GOLDEN_APPLE
  - MACE
  - HEAVY_CORE
  - TRIAL_KEY
  - OMINOUS_TRIAL_KEY
  - SCULK_SHRIEKER
  - NETHER_STAR
  - PLAYER_HEAD
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - ZOMBIE_HEAD
  - CREEPER_HEAD
  - PIGLIN_HEAD
  - ENDER_DRAGON_HEAD
  - SPAWNER
